CREATE TABLE users (
name VARCHAR(100) NOT NULL,
phone VARCHAR(20) NOT NULL,
cpf VARCHAR(15) PRIMARY KEY NOT NULL,
zipCode VARCHAR(20) NOT NULL,
logradouro VARCHAR(255) NOT NULL,
city VARCHAR(50) NOT NULL,
state VARCHAR(50) NOT NULL,
creation_date TIMESTAMP NOT NULL DEFAULT Current_date);