version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: projetouser1234
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server --requirepass projetouserredis
    ports:
      - 6379:6379